#!/bin/bash

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
polybar main &
/usr/lib/kdeconnectd &
dunst &
easyeffects --gapplication-service &
picom -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           6
bspc config bottom_padding       32
bspc config normal_border_color  '#3c3836'
bspc config focused_border_color '#83a598'
